INPUT:
  SIZE: (32, 32)
  TRANSFORMS: ['random_flip', 'random_crop', 'normalize']
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  CROP_PADDING: 4

DATASET:
  NAME: 'CIFAR100'
  NUM_LABELED: 10000
  VAL_PERCENT: 0.

MODEL:
  BACKBONE:
    NAME: 'wide_resnet_28_2'