INPUT:
  SIZE: (96, 96)
  TRANSFORMS: ['random_flip', 'random_crop', 'normalize']
  PIXEL_MEAN: [0.5, 0.5, 0.5]
  PIXEL_STD: [0.5, 0.5, 0.5]
  CROP_PADDING: 4

DATASET:
  NAME: 'STL10'
  STL10_FOLD: 0

MODEL:
  BACKBONE:
    NAME: 'wide_resnet_28_2'