INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ['random_flip', 'random_translation', 'normalize']

DATASET:
  NAME: 'SSDGPACS'
  NUM_LABELED: 210

MODEL:
  BACKBONE:
    NAME: 'resnet18'
    PRETRAINED: True